//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.1433
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace xmlparsing
{
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3schools.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3schools.com", IsNullable=false)]
    public partial class objects {
        
        private object[] itemsField;
        
        private bool defaultlazyinitField;
        
        private objectsDefaultdependencycheck defaultdependencycheckField;
        
        private objectsDefaultautowire defaultautowireField;
        
        public objects() {
            this.defaultlazyinitField = false;
            this.defaultdependencycheckField = objectsDefaultdependencycheck.none;
            this.defaultautowireField = objectsDefaultautowire.no;
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("alias", typeof(aliasElement))]
        [System.Xml.Serialization.XmlElementAttribute("description", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("import", typeof(importElement))]
        [System.Xml.Serialization.XmlElementAttribute("object", typeof(vanillaObject))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("default-lazy-init")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool defaultlazyinit {
            get {
                return this.defaultlazyinitField;
            }
            set {
                this.defaultlazyinitField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("default-dependency-check")]
        [System.ComponentModel.DefaultValueAttribute(objectsDefaultdependencycheck.none)]
        public objectsDefaultdependencycheck defaultdependencycheck {
            get {
                return this.defaultdependencycheckField;
            }
            set {
                this.defaultdependencycheckField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("default-autowire")]
        [System.ComponentModel.DefaultValueAttribute(objectsDefaultautowire.no)]
        public objectsDefaultautowire defaultautowire {
            get {
                return this.defaultautowireField;
            }
            set {
                this.defaultautowireField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public partial class aliasElement {
        
        private string nameField;
        
        private string aliasField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public partial class mapEntryElement {
        
        private mapKeyElement keyField;
        
        private string descriptionField;
        
        private object itemField;
        
        private ItemChoiceType2 itemElementNameField;
        
        private string key1Field;
        
        private string valueField;
        
        private string keyrefField;
        
        private string valuerefField;
        
        /// <comentarios/>
        public mapKeyElement key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <comentarios/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("dictionary", typeof(objectMap))]
        [System.Xml.Serialization.XmlElementAttribute("idref", typeof(objectReference))]
        [System.Xml.Serialization.XmlElementAttribute("list", typeof(constructorArgumentList))]
        [System.Xml.Serialization.XmlElementAttribute("name-values", typeof(objectNameValues))]
        [System.Xml.Serialization.XmlElementAttribute("null", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("object", typeof(vanillaObject))]
        [System.Xml.Serialization.XmlElementAttribute("ref", typeof(objectReference))]
        [System.Xml.Serialization.XmlElementAttribute("set", typeof(constructorArgumentListSet))]
        [System.Xml.Serialization.XmlElementAttribute("value", typeof(valueObject))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("key")]
        public string key1 {
            get {
                return this.key1Field;
            }
            set {
                this.key1Field = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("key-ref")]
        public string keyref {
            get {
                return this.keyrefField;
            }
            set {
                this.keyrefField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("value-ref")]
        public string valueref {
            get {
                return this.valuerefField;
            }
            set {
                this.valuerefField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public partial class mapKeyElement {
        
        private string descriptionField;
        
        private object itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        /// <comentarios/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("dictionary", typeof(objectMap))]
        [System.Xml.Serialization.XmlElementAttribute("idref", typeof(objectReference))]
        [System.Xml.Serialization.XmlElementAttribute("list", typeof(constructorArgumentList))]
        [System.Xml.Serialization.XmlElementAttribute("name-values", typeof(objectNameValues))]
        [System.Xml.Serialization.XmlElementAttribute("null", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("object", typeof(vanillaObject))]
        [System.Xml.Serialization.XmlElementAttribute("ref", typeof(objectReference))]
        [System.Xml.Serialization.XmlElementAttribute("set", typeof(constructorArgumentListSet))]
        [System.Xml.Serialization.XmlElementAttribute("value", typeof(valueObject))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public partial class objectMap {
        
        private mapEntryElement[] entryField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("entry")]
        public mapEntryElement[] entry {
            get {
                return this.entryField;
            }
            set {
                this.entryField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public partial class objectReference {
        
        private string objectField;
        
        private string localField;
        
        private string parentField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string local {
            get {
                return this.localField;
            }
            set {
                this.localField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3schools.com")]
    public partial class constructorArgumentList {
        
        private string[] descriptionField;
        
        private object[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public string[] description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("dictionary", typeof(objectMap))]
        [System.Xml.Serialization.XmlElementAttribute("idref", typeof(objectReference))]
        [System.Xml.Serialization.XmlElementAttribute("list", typeof(constructorArgumentList))]
        [System.Xml.Serialization.XmlElementAttribute("name-values", typeof(objectNameValues))]
        [System.Xml.Serialization.XmlElementAttribute("null", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("object", typeof(vanillaObject))]
        [System.Xml.Serialization.XmlElementAttribute("ref", typeof(objectReference))]
        [System.Xml.Serialization.XmlElementAttribute("set", typeof(constructorArgumentListSet))]
        [System.Xml.Serialization.XmlElementAttribute("value", typeof(valueObject))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public partial class objectNameValues {
        
        private objectNameValuesAdd[] addField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("add")]
        public objectNameValuesAdd[] add {
            get {
                return this.addField;
            }
            set {
                this.addField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3schools.com")]
    public partial class objectNameValuesAdd {
        
        private string keyField;
        
        private string valueField;
        
        private string[] textField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public partial class vanillaObject {
        
        private string descriptionField;
        
        private constructorArgument[] constructorargField;
        
        private property[] propertyField;
        
        private vanillaObjectListener[] listenerField;
        
        private string idField;
        
        private string nameField;
        
        private string typeField;
        
        private string parentField;
        
        private bool abstractField;
        
        private bool singletonField;
        
        private vanillaObjectScope scopeField;
        
        private vanillaObjectLazyinit lazyinitField;
        
        private vanillaObjectAutowire autowireField;
        
        private vanillaObjectDependencycheck dependencycheckField;
        
        private string dependsonField;
        
        private string initmethodField;
        
        private string destroymethodField;
        
        private string factorymethodField;
        
        private string factoryobjectField;
        
        public vanillaObject() {
            this.abstractField = false;
            this.singletonField = true;
            this.scopeField = vanillaObjectScope.application;
            this.lazyinitField = vanillaObjectLazyinit.@default;
            this.autowireField = vanillaObjectAutowire.@default;
            this.dependencycheckField = vanillaObjectDependencycheck.@default;
        }
        
        /// <comentarios/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("constructor-arg")]
        public constructorArgument[] constructorarg {
            get {
                return this.constructorargField;
            }
            set {
                this.constructorargField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("property")]
        public property[] property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("listener")]
        public vanillaObjectListener[] listener {
            get {
                return this.listenerField;
            }
            set {
                this.listenerField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool @abstract {
            get {
                return this.abstractField;
            }
            set {
                this.abstractField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool singleton {
            get {
                return this.singletonField;
            }
            set {
                this.singletonField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(vanillaObjectScope.application)]
        public vanillaObjectScope scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("lazy-init")]
        [System.ComponentModel.DefaultValueAttribute(vanillaObjectLazyinit.@default)]
        public vanillaObjectLazyinit lazyinit {
            get {
                return this.lazyinitField;
            }
            set {
                this.lazyinitField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(vanillaObjectAutowire.@default)]
        public vanillaObjectAutowire autowire {
            get {
                return this.autowireField;
            }
            set {
                this.autowireField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("dependency-check")]
        [System.ComponentModel.DefaultValueAttribute(vanillaObjectDependencycheck.@default)]
        public vanillaObjectDependencycheck dependencycheck {
            get {
                return this.dependencycheckField;
            }
            set {
                this.dependencycheckField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("depends-on")]
        public string dependson {
            get {
                return this.dependsonField;
            }
            set {
                this.dependsonField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("init-method")]
        public string initmethod {
            get {
                return this.initmethodField;
            }
            set {
                this.initmethodField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("destroy-method")]
        public string destroymethod {
            get {
                return this.destroymethodField;
            }
            set {
                this.destroymethodField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("factory-method")]
        public string factorymethod {
            get {
                return this.factorymethodField;
            }
            set {
                this.factorymethodField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("factory-object")]
        public string factoryobject {
            get {
                return this.factoryobjectField;
            }
            set {
                this.factoryobjectField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public partial class constructorArgument {
        
        private string descriptionField;
        
        private object itemField;
        
        private ItemChoiceType3 itemElementNameField;
        
        private string nameField;
        
        private string indexField;
        
        private string typeField;
        
        private string valueField;
        
        private string refField;
        
        /// <comentarios/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("dictionary", typeof(objectMap))]
        [System.Xml.Serialization.XmlElementAttribute("idref", typeof(objectReference))]
        [System.Xml.Serialization.XmlElementAttribute("list", typeof(constructorArgumentList))]
        [System.Xml.Serialization.XmlElementAttribute("name-values", typeof(objectNameValues))]
        [System.Xml.Serialization.XmlElementAttribute("null", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("object", typeof(vanillaObject))]
        [System.Xml.Serialization.XmlElementAttribute("ref", typeof(objectReference))]
        [System.Xml.Serialization.XmlElementAttribute("set", typeof(constructorArgumentListSet))]
        [System.Xml.Serialization.XmlElementAttribute("value", typeof(valueObject))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType3 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3schools.com")]
    public partial class constructorArgumentListSet {
        
        private string[] descriptionField;
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public string[] description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("dictionary", typeof(objectMap))]
        [System.Xml.Serialization.XmlElementAttribute("idref", typeof(objectReference))]
        [System.Xml.Serialization.XmlElementAttribute("list", typeof(constructorArgumentList))]
        [System.Xml.Serialization.XmlElementAttribute("name-values", typeof(objectNameValues))]
        [System.Xml.Serialization.XmlElementAttribute("null", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("object", typeof(vanillaObject))]
        [System.Xml.Serialization.XmlElementAttribute("ref", typeof(objectReference))]
        [System.Xml.Serialization.XmlElementAttribute("set", typeof(constructorArgumentListSet))]
        [System.Xml.Serialization.XmlElementAttribute("value", typeof(valueObject))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public partial class valueObject {
        
        private string typeField;
        
        private string valueField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <comentarios/>
        dictionary,
        
        /// <comentarios/>
        idref,
        
        /// <comentarios/>
        list,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("name-values")]
        namevalues,
        
        /// <comentarios/>
        @null,
        
        /// <comentarios/>
        @object,
        
        /// <comentarios/>
        @ref,
        
        /// <comentarios/>
        set,
        
        /// <comentarios/>
        value,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com", IncludeInSchema=false)]
    public enum ItemChoiceType3 {
        
        /// <comentarios/>
        dictionary,
        
        /// <comentarios/>
        idref,
        
        /// <comentarios/>
        list,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("name-values")]
        namevalues,
        
        /// <comentarios/>
        @null,
        
        /// <comentarios/>
        @object,
        
        /// <comentarios/>
        @ref,
        
        /// <comentarios/>
        set,
        
        /// <comentarios/>
        value,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public partial class property {
        
        private string descriptionField;
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private string nameField;
        
        private string valueField;
        
        private string refField;
        
        /// <comentarios/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("dictionary", typeof(objectMap))]
        [System.Xml.Serialization.XmlElementAttribute("idref", typeof(objectReference))]
        [System.Xml.Serialization.XmlElementAttribute("list", typeof(constructorArgumentList))]
        [System.Xml.Serialization.XmlElementAttribute("name-values", typeof(objectNameValues))]
        [System.Xml.Serialization.XmlElementAttribute("null", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("object", typeof(vanillaObject))]
        [System.Xml.Serialization.XmlElementAttribute("ref", typeof(objectReference))]
        [System.Xml.Serialization.XmlElementAttribute("set", typeof(constructorArgumentListSet))]
        [System.Xml.Serialization.XmlElementAttribute("value", typeof(valueObject))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <comentarios/>
        dictionary,
        
        /// <comentarios/>
        idref,
        
        /// <comentarios/>
        list,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("name-values")]
        namevalues,
        
        /// <comentarios/>
        @null,
        
        /// <comentarios/>
        @object,
        
        /// <comentarios/>
        @ref,
        
        /// <comentarios/>
        set,
        
        /// <comentarios/>
        value,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3schools.com")]
    public partial class vanillaObjectListener {
        
        private objectOrClassReference[] refField;
        
        private string eventField;
        
        private string methodField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("ref")]
        public objectOrClassReference[] @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public partial class objectOrClassReference {
        
        private string objectField;
        
        private string localField;
        
        private string typeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string local {
            get {
                return this.localField;
            }
            set {
                this.localField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3schools.com")]
    public enum vanillaObjectScope {
        
        /// <comentarios/>
        application,
        
        /// <comentarios/>
        session,
        
        /// <comentarios/>
        request,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3schools.com")]
    public enum vanillaObjectLazyinit {
        
        /// <comentarios/>
        @true,
        
        /// <comentarios/>
        @false,
        
        /// <comentarios/>
        @default,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3schools.com")]
    public enum vanillaObjectAutowire {
        
        /// <comentarios/>
        no,
        
        /// <comentarios/>
        byName,
        
        /// <comentarios/>
        byType,
        
        /// <comentarios/>
        constructor,
        
        /// <comentarios/>
        autodetect,
        
        /// <comentarios/>
        @default,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3schools.com")]
    public enum vanillaObjectDependencycheck {
        
        /// <comentarios/>
        none,
        
        /// <comentarios/>
        objects,
        
        /// <comentarios/>
        simple,
        
        /// <comentarios/>
        all,
        
        /// <comentarios/>
        @default,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <comentarios/>
        dictionary,
        
        /// <comentarios/>
        idref,
        
        /// <comentarios/>
        list,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("name-values")]
        namevalues,
        
        /// <comentarios/>
        @null,
        
        /// <comentarios/>
        @object,
        
        /// <comentarios/>
        @ref,
        
        /// <comentarios/>
        set,
        
        /// <comentarios/>
        value,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <comentarios/>
        dictionary,
        
        /// <comentarios/>
        idref,
        
        /// <comentarios/>
        list,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("name-values")]
        namevalues,
        
        /// <comentarios/>
        @null,
        
        /// <comentarios/>
        @object,
        
        /// <comentarios/>
        @ref,
        
        /// <comentarios/>
        set,
        
        /// <comentarios/>
        value,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com", IncludeInSchema=false)]
    public enum ItemChoiceType2 {
        
        /// <comentarios/>
        dictionary,
        
        /// <comentarios/>
        idref,
        
        /// <comentarios/>
        list,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("name-values")]
        namevalues,
        
        /// <comentarios/>
        @null,
        
        /// <comentarios/>
        @object,
        
        /// <comentarios/>
        @ref,
        
        /// <comentarios/>
        set,
        
        /// <comentarios/>
        value,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public partial class importElement {
        
        private string resourceField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string resource {
            get {
                return this.resourceField;
            }
            set {
                this.resourceField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3schools.com")]
    public enum objectsDefaultdependencycheck {
        
        /// <comentarios/>
        none,
        
        /// <comentarios/>
        objects,
        
        /// <comentarios/>
        simple,
        
        /// <comentarios/>
        all,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3schools.com")]
    public enum objectsDefaultautowire {
        
        /// <comentarios/>
        no,
        
        /// <comentarios/>
        byName,
        
        /// <comentarios/>
        byType,
        
        /// <comentarios/>
        constructor,
        
        /// <comentarios/>
        autodetect,
    }
}
